site_name: kedro-psutil-telemetry
site_description: Kedro hook to trace system resources during pipeline execution via pluggable sinks
site_author: Simon Niederberger
site_url: https://saemeon.github.io/kedro-psutil-telemetry/

repo_url: https://github.com/saemeon/kedro-psutil-telemetry
repo_name: saemeon/kedro-psutil-telemetry

copyright: "Copyright &copy; 2026 Simon Niederberger"

nav:
  - Overview: "index.md"
  - API Reference: "api.md"

theme:
  name: material
  features:
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - navigation.top
    - navigation.tracking
    - content.action.edit
    - search.highlight
    - search.suggest
  icon:
    repo: fontawesome/brands/github
    edit: material/eye
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            docstring_style: numpy
            docstring_section_style: spacy
            show_if_no_docstring: false
            show_root_toc_entry: false
            show_source: false
            heading_level: 3
            show_symbol_type_heading: true
            show_symbol_type_toc: false
            merge_init_into_class: true
            show_signature: true
            separate_signature: true
            annotations_path: source
            filters: ["!^_[^_]"]
  - mike:
      canonical_version: latest
      alias_type: redirect
      version_selector: true
      css_dir: css
      javascript_dir: js

watch:
  - src

remote_branch: documentation

extra:
  version:
    provider: mike
    alias: true
    default: latest
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/saemeon/kedro-psutil-telemetry
